// ============================================================
// DEALS CATALOG
//
// IMPORTANT: This is SAMPLE data to show the site working.
// Before launch, verify every offer on the company's own site
// and set verified: true. Replace each url with your affiliate
// link once you've joined that company's program.
//
// Fields:
//   popular    — true = shows on the homepage "Popular deals" view
//   pricing    — "free" | "freemium" | "trial" | "discount" (drives the Free filter)
//   price      — short price string shown on cards ("Free", "Free tier · Pro $20/mo").
//                Prices marked ~ are approximate — confirm before launch.
//   details    — "What you get" bullets on the deal page. Keep them factual
//                and specific (limits, trial lengths, eligibility).
//   rating     — Trustpilot score scraped on the date in `checked`. Refresh
//                periodically. Under 20 reviews the UI hides the score.
//   trial      — true = also has a free trial of a paid plan
//   trialLength— free-trial duration string (e.g. "30-day Pro trial"); shows a pill on the card
//   screenshot — true = show a live screenshot of the tool's site (opt-in)
//   image      — card/hero image (vendor og image or press-kit PNG/GIF)
//   gallery    — extra images for the deal page thumbnail strip (optional)
// ============================================================

const DEALS = [
  {
    name: "GitHub Student Developer Pack",
    category: "Coding",
    deal: "Free with a school email",
    price: "Free for students",
    description: "GitHub Copilot Pro plus dozens of dev tools, free while you're a student. The single best student bundle on the internet.",
    details: [
      "GitHub Copilot Pro free while you're a verified student",
      "Dozens of partner tools included: cloud credits, free domains, IDEs, and more",
      "Free for as long as you're enrolled — re-verify each year",
      "Requires proof of enrollment (school email or student ID)",
    ],
    url: "https://education.github.com/pack",
    image: "images/github.png",
    rating: { score: 2.0, count: 253, source: "Trustpilot", url: "https://www.trustpilot.com/review/github.com", checked: "2026-07-23" },
    pricing: "free",
    popular: true,
    screenshot: true,
    verified: false,
  },
  {
    name: "Notion",
    category: "Productivity",
    deal: "Free Plus plan for students",
    price: "Free for students",
    description: "Notes, docs, and planning with Notion AI available as an add-on. The education plan is free with a school email.",
    details: [
      "Education Plus plan free with a school email",
      "Unlimited pages and blocks, file uploads, and version history",
      "Notion AI is a paid add-on — not included in the free education plan",
      "Free for as long as you have a valid school email",
    ],
    url: "https://www.notion.so/students",
    image: "images/notion.png",
    rating: { score: 2.3, count: 418, source: "Trustpilot", url: "https://www.trustpilot.com/review/notion.so", checked: "2026-07-23" },
    pricing: "free",
    popular: true,
    screenshot: true,
    verified: false,
  },
  {
    name: "Perplexity",
    category: "Research",
    deal: "Student offer",
    price: "Free tier · Pro $20/mo",
    description: "AI answer engine with cited sources — great for research without the hallucinated citations. Runs student promotions on Pro.",
    details: [
      "Free tier: unlimited quick searches with cited sources",
      "Pro: more advanced searches per day, file uploads, and model choice",
      "Runs student promotions on Pro periodically — check their site",
    ],
    url: "https://www.perplexity.ai/",
    image: "images/perplexity.jpg",
    rating: { score: 1.5, count: 714, source: "Trustpilot", url: "https://www.trustpilot.com/review/perplexity.ai", checked: "2026-07-23" },
    pricing: "discount",
    popular: true,
    verified: false,
  },
  {
    name: "Grammarly",
    category: "Writing",
    deal: "Free tier + education plans",
    price: "Free tier · Premium ~$12/mo",
    description: "Grammar, tone, and clarity checking everywhere you write. Solid free tier; some schools cover Premium.",
    details: [
      "Free: grammar, spelling, and tone basics everywhere you write",
      "Premium: full-sentence rewrites, plagiarism detection, citation support",
      "Premium is ~$12/mo billed annually — but check if your school licenses it for free first",
    ],
    url: "https://www.grammarly.com/edu",
    image: "images/grammarly.png",
    rating: { score: 3.3, count: 10461, source: "Trustpilot", url: "https://www.trustpilot.com/review/grammarly.com", checked: "2026-07-23" },
    pricing: "freemium",
    popular: true,
    verified: false,
  },
  {
    name: "Quizlet",
    category: "Studying",
    deal: "Free tier + Plus discount",
    price: "Free tier · Plus ~$7.99/mo",
    description: "Flashcards and practice tests with AI-generated study modes from your own notes.",
    details: [
      "Free: flashcards, practice tests, and basic study modes",
      "Plus: ad-free, offline access, and unlimited AI-powered study modes",
      "New users typically get a free trial of Plus — length varies by promo",
    ],
    url: "https://quizlet.com/",
    rating: { score: 1.3, count: 640, source: "Trustpilot", url: "https://www.trustpilot.com/review/quizlet.com", checked: "2026-07-23" },
    pricing: "freemium",
    trial: true,
    popular: true,
    verified: false,
  },
  {
    name: "Otter.ai",
    category: "Productivity",
    deal: "Education discount",
    price: "Free tier · student discount on Pro",
    description: "Records and transcribes lectures in real time, then gives you an AI summary and searchable notes.",
    details: [
      "Free: 300 transcription minutes per month, 30 min per conversation",
      "Pro: 1,200 minutes/month, longer conversations, better exports",
      "Students and teachers get a discount on Pro with a school email",
    ],
    url: "https://otter.ai/education",
    image: "images/otter.png",
    rating: { score: 3.1, count: 570, source: "Trustpilot", url: "https://www.trustpilot.com/review/otter.ai", checked: "2026-07-23" },
    pricing: "discount",
    popular: false,
    verified: false,
  },
  {
    name: "Gamma",
    category: "Design",
    deal: "Generous free tier",
    price: "Free tier · paid from ~$8/mo",
    description: "Generates full slide decks from a prompt. The fastest way to turn an outline into a presentation.",
    details: [
      "Free: AI deck generation with starting credits, share and present online",
      "Paid plans: unlimited AI creation and watermark-free exports",
      "No credit card needed for the free tier",
    ],
    url: "https://gamma.app/",
    image: "images/gamma.png",
    rating: { score: 1.7, count: 118, source: "Trustpilot", url: "https://www.trustpilot.com/review/gamma.app", checked: "2026-07-23" },
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Wolfram|Alpha Pro",
    category: "Studying",
    deal: "Student pricing",
    price: "Student plan from ~$5/mo",
    description: "Step-by-step math solutions, not just answers. Discounted Pro plan for students.",
    details: [
      "Pro: step-by-step solutions for math, physics, and chemistry problems",
      "Practice problems with hints, and photo input for handwritten math",
      "Discounted student pricing — cheaper than a single tutoring session per year",
    ],
    url: "https://www.wolframalpha.com/pro/pricing/students",
    image: "images/wolfram.png",
    rating: { score: 3.3, count: 3, source: "Trustpilot", url: "https://www.trustpilot.com/review/wolframalpha.com", checked: "2026-07-23" },
    pricing: "discount",
    popular: false,
    verified: false,
  },
  {
    name: "Speechify",
    category: "Studying",
    deal: "Free tier",
    price: "Free tier · Premium ~$139/yr",
    description: "Turns readings and PDFs into natural-sounding audio so you can get through them faster.",
    details: [
      "Free: listen to docs, PDFs, and web pages at standard speeds",
      "Premium: natural AI voices, up to 4.5x speed, scan-and-listen for printed pages",
      "Works across phone, browser extension, and desktop",
    ],
    url: "https://speechify.com/",
    image: "images/speechify.jpg",
    rating: { score: 4.7, count: 6662, source: "Trustpilot", url: "https://www.trustpilot.com/review/speechify.com", checked: "2026-07-23" },
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Zotero",
    category: "Research",
    deal: "100% free",
    price: "Free",
    description: "The standard tool for collecting sources and generating citations. Free and open source, with AI plugins available.",
    details: [
      "Completely free, open-source citation manager — no premium upsell",
      "Browser connector saves any source in one click",
      "Word and Google Docs plugins generate citations and bibliographies",
      "Paid only if you want extra cloud sync storage (from $20/yr)",
    ],
    url: "https://www.zotero.org/",
    rating: { score: 3.7, count: 14, source: "Trustpilot", url: "https://www.trustpilot.com/review/zotero.org", checked: "2026-07-23" },
    pricing: "free",
    popular: false,
    screenshot: true,
    verified: false,
  },
  {
    name: "Canva",
    category: "Design",
    deal: "Free tier + Pro trial",
    price: "Free tier · Pro ~$13/mo",
    description: "Design anything — posters, decks, social posts — with built-in AI image and text tools.",
    details: [
      "Free: thousands of templates and basic AI design tools",
      "Pro: premium assets, background remover, brand kits, and more AI credits",
      "30-day free trial of Pro",
      "Heads up: Canva's free education program covers K-12 only, not college",
    ],
    url: "https://www.canva.com/education/",
    image: "images/canva.jpg",
    rating: { score: 4.0, count: 6130, source: "Trustpilot", url: "https://www.trustpilot.com/review/canva.com", checked: "2026-07-23" },
    pricing: "freemium",
    trial: true,
    trialLength: "30-day Pro trial",
    popular: false,
    verified: false,
  },
  {
    name: "ChatGPT",
    category: "Writing",
    deal: "Free tier",
    price: "Free · Plus $20/mo",
    description: "The general-purpose assistant everyone knows. The free tier covers a lot of student use cases.",
    details: [
      "Free: full chat access with daily usage limits",
      "Plus: higher limits, stronger models, file uploads, and image generation",
      "No student discount currently — the free tier is the student play",
    ],
    url: "https://chatgpt.com/",
    image: "images/chatgpt.png",
    rating: { score: 1.2, count: 1094, source: "Trustpilot", url: "https://www.trustpilot.com/review/openai.com", checked: "2026-07-23" },
    pricing: "freemium",
    popular: true,
    verified: false,
  },
  {
    name: "Claude",
    category: "Writing",
    deal: "Free tier + free Pro at partner schools",
    price: "Free tier · Pro $20/mo",
    description: "Claude is an AI assistant for writing, research, and coding with a genuinely usable free tier. Students at universities with a Claude for Education license get Pro-level features free by signing in with their school email; there's no personal student discount otherwise.",
    details: [
      "Free tier ($0): chat, web search, file uploads, memory, and Projects, but with capped usage limits that tighten during high demand",
      "Pro is $20/mo billed monthly, or $17/mo on annual billing (per claude.com/pricing) — check their site as prices change",
      "No individual student discount; Claude for Education gives free Pro only if your university holds a license — sign in with your .edu email to check",
      "No time-limited free trial on Pro; the free tier is the way to try it",
    ],
    url: "https://claude.ai",
    rating: { score: 1.5, count: 1695, source: "Trustpilot", url: "https://www.trustpilot.com/review/claude.ai", checked: "2026-07-23" },
    pricing: "freemium",
    popular: true,
    verified: false,
  },
  {
    name: "Google Gemini",
    category: "Research",
    deal: "Free tier + 1-month Pro trial",
    price: "Free tier · Pro $19.99/mo",
    description: "Google's AI assistant for writing, coding, and studying, with a Deep Research mode that pulls together and summarizes sources. Free with any Google account; paid plans add stronger models, higher usage limits, and more storage.",
    details: [
      "Free tier (any Google account): chat, image generation, Canvas and Gems on Gemini Flash, plus Deep Research (about 5 reports/month) and 15 GB storage, with daily usage limits",
      "Google AI Pro is $19.99/mo — adds the top Gemini 3 Pro model, higher limits, Veo video, and Gemini in Gmail, Docs and Sheets; first-time users get a 1-month free trial that auto-renews",
      "A cheaper Google AI Plus tier is $4.99/mo (2x limits, 200 GB storage) if Pro is more than you need",
      "Google's year-long free AI Pro student offer has ended — no current student discount is confirmed, so check their site",
    ],
    url: "https://gemini.google.com/",
    pricing: "freemium",
    trial: true,
    trialLength: "1-month Pro trial",
    popular: true,
    verified: false,
  },
  {
    name: "Cursor",
    category: "Coding",
    deal: "Free Hobby tier (no card)",
    price: "Free tier · Pro $20/mo (~$16/mo annual)",
    description: "Cursor is an AI-powered code editor (a VS Code fork) that autocompletes and rewrites code from chat. Students can code for free on the Hobby tier with no credit card, then decide whether Pro is worth $20/mo.",
    details: [
      "Free Hobby tier: no credit card, but limited AI Agent requests and limited Tab completions",
      "Pro is $20/mo month-to-month, or ~$16/mo billed annually (20% off) — check their site to confirm",
      "New accounts may get a short full-Pro trial, but the official pricing page lists none and reports conflict in 2026 — don't count on it",
      "Student gotcha: the free-year student Pro offer closed to new signups on June 25, 2026; now only occasional campus/event credits, so no reliable universal student discount",
    ],
    url: "https://cursor.com/",
    pricing: "freemium",
    popular: true,
    verified: false,
  },
  {
    name: "Overleaf",
    category: "Studying",
    deal: "Free tier + student discount",
    price: "Free tier · Student $10/mo",
    description: "Overleaf is a browser-based LaTeX editor for writing papers, theses, and problem sets with real-time collaboration and no local setup. The free tier covers solo writing, and there's a discounted student plan — but check whether your university already provides Overleaf Professional for free before paying.",
    details: [
      "Free plan: unlimited projects but only 1 collaborator per project, a short compile-timeout limit, and AI assist capped at 5 uses/day",
      "Student plan $10/mo (or $98/yr, ~18% off) adds 10 collaborators and a much longer compile timeout; requires verified enrollment",
      "Non-student tiers: Standard $21/mo ($199/yr) and Professional $42/mo ($399/yr); annual billing saves ~20%",
      "Many universities offer Overleaf Professional free through a campus/library site license — check with your school before subscribing",
    ],
    url: "https://www.overleaf.com",
    pricing: "freemium",
    trial: true,
    trialLength: "7-day trial",
    popular: false,
    verified: false,
  },
  {
    name: "QuillBot",
    category: "Writing",
    deal: "Free tier + student discount",
    price: "Free tier · Premium $20/mo ($8/mo annual)",
    description: "QuillBot is a paraphrasing and grammar tool for rewriting, summarizing, and cleaning up drafts. The free tier covers light use, and verified students can get Premium at a reduced annual rate.",
    details: [
      "Free tier: paraphraser capped at 125 words per run with 2 modes (Standard + Fluency) plus basic grammar checking — no credit card, no time limit",
      "Premium unlocks unlimited paraphrasing, all paraphrasing modes, and a plagiarism checker (25,000 words/mo); $19.95/mo monthly or $8.33/mo billed annually ($99.95/yr)",
      "Student discount: 25% off the annual plan (~$6.25/mo) with student/.edu email verification — confirm current price on their site",
      "No time-limited free trial; a 3-day money-back guarantee is the only refund window",
    ],
    url: "https://quillbot.com/premium",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Figma",
    category: "Design",
    deal: "Free Pro for verified students",
    price: "Free for students · Pro $20/mo",
    description: "Figma is a collaborative interface-design tool for UI design, prototyping, and FigJam whiteboarding. Verified higher-ed students and educators get the paid Professional plan free for a year (renewable), and there's a free Starter tier open to everyone.",
    details: [
      "Student deal: verified higher-ed students & educators get the full Professional plan free for 1 year from approval, renewable while eligible — apply with a school email and proof of enrollment",
      "Free Starter tier (no student status needed): 3 Figma Design + 3 FigJam files, 1 project, unlimited personal drafts, up to 2 editors/file, 30-day version history",
      "Paid Professional (non-students): $20/mo per full seat billed monthly, or $16/mo billed annually — check their site to confirm",
      "No time-limited free trial of paid plans; the free Starter tier is the entry point. Education access is region-limited and needs re-verification to renew",
    ],
    url: "https://www.figma.com/education/",
    pricing: "free",
    popular: true,
    verified: false,
  },
  {
    name: "NotebookLM",
    category: "Studying",
    deal: "Free tier + 1-month Pro trial",
    price: "Free tier · Plus ~$5/mo · Pro $20/mo",
    description: "Google's AI research assistant that turns your own PDFs, slides, and notes into summaries, study guides, quizzes, flashcards, and audio overviews, all grounded in the sources you upload. The free tier is generous enough for most coursework and needs no credit card.",
    details: [
      "Free forever tier: 100 notebooks, 50 sources each, 50 chats/day, and 3 audio + 3 video overviews per day — no card required",
      "Paid upgrades are bundled with Google's AI plans: NotebookLM Plus via Google AI Plus (~$5/mo) or NotebookLM Pro via Google AI Pro ($19.99/mo, raising limits to ~300 sources per notebook)",
      "Google AI Pro includes a 1-month free trial that unlocks Pro limits",
      "Gotcha: the free 12-month student offer ended April 30, 2026, and Google no longer lists a student-specific price — students pay standard rates or use the free tier",
    ],
    url: "https://notebooklm.google.com/",
    pricing: "freemium",
    trial: true,
    trialLength: "1-month Pro trial",
    popular: false,
    verified: false,
  },
  {
    name: "DeepL",
    category: "Writing",
    deal: "Free tier + 30-day trial",
    price: "Free tier · Individual $8.74/mo (annual)",
    description: "DeepL is an AI translation and writing tool that's handy for reading foreign-language sources and drafting text in another language. The free tier covers light coursework, and paid plans raise the character and document limits.",
    details: [
      "Free version: 50,000 characters/month plus 1 document translation/month (files up to 5 MB)",
      "Individual plan is $8.74/mo billed annually (monthly billing costs more, ~$10.40/mo) and adds 300,000 chars/month + 3 documents/month (up to 30 MB)",
      "Paid plans include a 30-day free trial, cancel anytime",
      "No student or education discount as of mid-2026; listed prices are USD and vary by region, so check their site",
    ],
    url: "https://www.deepl.com/pro",
    rating: { score: 2.4, count: 744, source: "Trustpilot", url: "https://www.trustpilot.com/review/www.deepl.com", checked: "2026-07-23" },
    pricing: "freemium",
    trial: true,
    trialLength: "30-day trial",
    popular: false,
    verified: false,
  },
  {
    name: "Knowt",
    category: "Studying",
    deal: "Free tier + 15% student discount",
    price: "Free tier · Ultra $24.99/mo or $149.99/yr",
    description: "Knowt is a free Quizlet alternative that turns your notes, PDFs, lectures, and videos into flashcards, quizzes, and study guides, with an AI assistant called Kai. The free tier covers everyday coursework; paid Ultra removes AI usage limits.",
    details: [
      "Free Basic plan: unlimited flashcards & notes, free study modes (Learn, matching, spaced repetition, practice tests), and browsing millions of pre-made sets — no credit card (AI features are usable but monthly-capped)",
      "Paid Ultra plan: $24.99/mo or $149.99/yr (~$12.49/mo effective) unlocks unlimited AI summaries, unlimited Kai chat, and auto-graded assessments",
      "Students get 15% off paid plans plus a 1-month free trial via verified programs (UNiDAYS / Student Beans)",
      "A standard (non-student) trial length isn't stated on the official plans page — third-party reviews say ~7 days; check their site before relying on it",
    ],
    url: "https://knowt.com",
    pricing: "freemium",
    trial: true,
    trialLength: "1-month student trial",
    popular: false,
    verified: false,
  },
  {
    name: "Thea",
    category: "Studying",
    deal: "Free for students",
    price: "Free tier · ~$10/mo ($40/yr)",
    description: "Thea is an AI study app that turns your notes, PDFs, lecture videos, or a pasted YouTube link into flashcards, quizzes, study guides, and practice tests. It's currently free for students, with an optional paid subscription for extra access.",
    details: [
      "Free tier: create a free account and use it for free — the pricing page explicitly says \"Students, it's FREE!\" (some sources describe this as free during beta, so it could change)",
      "Paid option: the iOS \"Early Access\" in-app subscription is ~$10/mo or ~$40/yr; there is no published web pricing table, so check their site",
      "Turns your own uploads — handwritten notes, PDFs, lecture videos, or a pasted YouTube link — into flashcards, quizzes, summaries, and tests using active recall",
      "No time-limited free trial; the free tier is the free access. Educators/institutions need a custom quote (email info@thea.study)",
    ],
    url: "https://www.thea.study",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "NotesXP",
    category: "Studying",
    deal: "Free tier + affordable Pro",
    price: "Free tier · Pro $9/mo · $59/yr",
    description: "NotesXP turns PDFs, textbook photos, and lecture recordings into structured notes, flashcards, quizzes, and mind maps. It's an Apple-only app (iPhone, iPad, Mac) with a free tier that needs no account.",
    details: [
      "Free tier gives core features with no required account and no ads, and iCloud sync is automatic; the exact free-tier cap on study sets isn't published — check their site",
      "Pro unlocks unlimited study sets for $9/mo or $59/yr as an Apple App Store in-app purchase; the website doesn't list prices, so confirm in-app",
      "No time-limited free trial, and no verified student/education discount — pricing is only marketed as 'student-friendly'",
      "Apple-only: iPhone/iPad (iOS 15.8+), Mac (macOS 13, M1+), and Apple Vision. No Android app and no web app",
    ],
    url: "https://notesxp.app/",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Mindomax",
    category: "Studying",
    deal: "Premium free until 2028",
    price: "Free tier · Premium free until 2028 (~$5.99/mo after)",
    description: "Mindomax turns PDFs, lecture audio, photos of notes, or plain text into flashcards with spaced repetition and an AI tutor. Its Premium plan is currently free for everyone through 2028.",
    details: [
      "Free tier: one box with unlimited cards, spaced-repetition scheduling, progress analytics, CSV export, and a basic AI assistant (search results cite a 3 AI-requests/day cap; not stated on the live pricing page)",
      "Premium: unlimited boxes, 90 daily AI requests, 450,000+ ready-made cards, PDF/audio/image card generation, LaTeX editor, and AI tutor",
      "Premium is currently free until 2028 (launch promo). The App Store lists a $5.99/mo Premium in-app purchase as the regular price; the website shows only '$0 free until 2028'",
      "No dedicated student/education discount found. Runs on web, iOS, Android, and Mac; launched Nov 2025",
    ],
    url: "https://www.mindomax.com/",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "BrainDen",
    category: "Studying",
    deal: "Free tier, no card needed",
    price: "Free tier · Pro ~$20/mo (~$100/yr)",
    description: "BrainDen turns your lectures, PDFs, videos, audio, and photos into AI-generated notes, flashcards, quizzes, and mind maps, with spaced repetition and a Feynman study mode. Free to start with no card required.",
    details: [
      "Free plan starts with no card: a small number of recordings (~3) plus AI notes, flashcards, quizzes, and mind maps",
      "Pro is $19.99/mo, $49.99 for 6 months, or $99.99/yr per the US App Store listing; web/subscription prices may differ, so check their site",
      "No time-limited free trial and no student/education discount were found; the free tier is the main student value",
      "Official site is brainden.app (app at learn.brainden.app) — 'brainden.ai' is not the real domain",
    ],
    url: "https://www.brainden.app/",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Solvo",
    category: "Studying",
    deal: "Free tier + 3-day trial",
    price: "Free tier · Premium ~$6.99/wk or ~$39.99/yr",
    description: "Solvo is a phone app that scans homework problems and returns step-by-step solutions across math, science, and writing, plus AI flashcards and quiz/test prep. A free tier covers occasional use, while a paid subscription lifts the daily usage limits.",
    details: [
      "Free tier lets you solve a limited number of problems per day; Premium removes usage limits and adds OCR scanning, longer answers, and faster responses",
      "3-day free trial that auto-renews into a weekly subscription (~$6.99/wk); a discounted annual plan (~$39.99/yr) is also offered — prices vary by region and promo, so check their site",
      "No student-specific discount or education program was found; this is a standard consumer app subscription (cancel before renewal to avoid charges)",
      "Official app is solvo.app (iOS/Android, by AIBY) — not solvo.ai, which is an unrelated freight/logistics company",
    ],
    url: "https://solvo.app/",
    pricing: "freemium",
    trial: true,
    trialLength: "3-day trial",
    popular: false,
    verified: false,
  },
  {
    name: "FlashRecall",
    category: "Studying",
    deal: "Free tier + paid Premium",
    price: "Free tier · Premium ~$15/mo (~$80/yr)",
    description: "FlashRecall turns your notes, PDFs, photos, audio, and YouTube links into AI flashcards and drills them with spaced repetition and active recall. A free tier covers light studying, and a paid Premium plan removes the AI-generation and review limits.",
    details: [
      "Free tier lets you create and study flashcards with limits for light studying; Premium unlocks unlimited AI generation and study sessions, plus offline access and cross-device sync",
      "Premium pricing isn't published on the site or App Store; third-party snippets suggest roughly $14.99/mo, $79.99/yr, or a ~$9.99/week option — unconfirmed, so check their site",
      "No dedicated student or education discount found; the app positions its ongoing free tier as the alternative to paid competitors' discounts",
      "No time-limited free trial — the free plan is ongoing but limited. Available on the iOS App Store and as a web app; made by TMBC Pte Ltd (Singapore)",
    ],
    url: "https://flashrecall.app/",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Replit",
    category: "Coding",
    deal: "Free tier + student discount on Core",
    price: "Free tier · Core $25/mo (students ~$10/mo)",
    description: "Browser-based coding platform with an AI Agent that builds and hosts full-stack apps — no local install, works on any device. The free Starter plan lets students prototype and publish one project without paying.",
    details: [
      "Free Starter plan: daily AI Agent credits, a built-in database, and publish up to 1 project (private or password-protected)",
      "Core is $25/mo, or $20/mo billed annually, with $25 in monthly usage credits and up to 5 collaborators",
      "Students reportedly get ~50% off Core (about $10/mo) with a .edu email, but it's not shown on Replit's own pricing page — check their site to confirm",
      "Runs entirely in the browser, so nothing to install on a school or personal laptop",
    ],
    url: "https://replit.com",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Google Colab",
    category: "Coding",
    deal: "Free cloud GPUs + free Pro year for US students",
    price: "Free tier · Pro $9.99/mo",
    description: "Google's browser-based Jupyter notebook environment that runs Python with free access to GPUs and TPUs, no local setup. Widely used for coursework, data science, and machine learning projects.",
    details: [
      "Free tier: browser notebooks with free (but availability-limited) GPU/TPU access, up to ~12h runtime, and idle timeouts",
      "Paid upgrades: Colab Pro $9.99/mo and Pro+ $49.99/mo for faster GPUs, more memory, and longer/background runtimes",
      "Pay As You Go: buy compute units (~$9.99 per 100 units) instead of a subscription — check their site",
      "Student angle: verified US students & faculty can currently get Colab Pro free for 1 year (limited spots, .edu verification); offer active as of 2026",
    ],
    url: "https://colab.research.google.com",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Windsurf",
    category: "Coding",
    deal: "Generous free tier",
    price: "Free tier · Pro $20/mo",
    description: "Codeium became Windsurf and is now Devin Desktop (Cognition), an AI coding editor with autocomplete plus built-in coding agents. The free plan gives unlimited Tab autocomplete and inline edits plus a light daily agent quota - enough for casual student use.",
    details: [
      "Free tier: unlimited Tab autocomplete and inline edits that don't touch quota, plus unlimited use of the fast SWE-1.6 model",
      "Free tier also includes a light daily agent/chat quota with limited model access (roughly a couple days of active agentic coding before it runs dry)",
      "Paid: Pro $20/mo, Max $200/mo (pricing moved to daily/weekly quotas in March 2026 - check their site)",
      "Student angle: an old Windsurf ~50% off Pro (.edu) offer existed, but the student page now redirects and it's unconfirmed under Devin - check their site",
    ],
    url: "https://devin.ai/desktop",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "v0 by Vercel",
    category: "Coding",
    deal: "1 year free for students",
    price: "Free tier · Plus $30/mo",
    description: "v0 is Vercel's AI app builder that turns plain-text prompts into working web UIs and full-stack code you can deploy. The free plan gives you monthly credits to build with, and verified students get a full year of the paid plan at no cost.",
    details: [
      "Free plan: $5 of included credits each month, capped at 7 messages/day; no API access or credit top-ups",
      "Includes deploy-to-Vercel, Design Mode visual editing, and GitHub sync even on free",
      "Students: 1 year of free v0 Premium via a verified student email (.edu) at ~14 participating schools (Stanford, MIT, Harvard, UC Berkeley, and more)",
      "Cheapest generally-available paid tier is Plus at $30/user/mo; Business $100/user/mo, Enterprise custom",
    ],
    url: "https://v0.app",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Bolt.new",
    category: "Coding",
    deal: "Generous free tier",
    price: "Free tier · Pro $25/mo",
    description: "Bolt.new turns plain-English chat prompts into full web apps and sites, handling the code, hosting, and database for you. The free plan lets you prototype small projects each month with no credit card, though the token allowance gets used up quickly on larger builds.",
    details: [
      "Free tier: $0, 1M tokens/month with a 300K daily cap, no credit card; includes public/private projects, website hosting, and unlimited databases (confirmed on official pricing page)",
      "Pro $25/mo (10M tokens/month with rollover, custom domains, removes Bolt branding); Teams $30/member/mo",
      "Free tokens do not roll over and reset at the start of each month",
      "Students: 2026 sources report ~50% off Pro via SheerID verification (educators get Pro free), but it is not shown on the public pricing page — verify eligibility on their site",
    ],
    url: "https://bolt.new",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Microsoft Copilot",
    category: "Productivity",
    deal: "Genuine free tier",
    price: "Free · M365 Premium $19.99/mo",
    description: "Microsoft's AI assistant with a genuinely free chat tier for research, writing help, coding questions, and image generation. Works on the web, in Windows and Edge, and on mobile, with deeper Office-app integration on paid plans.",
    details: [
      "Free Copilot Chat: web-grounded conversations for writing, study, and coding help, plus image generation via Designer (~15 boosts before it slows; sources differ on daily vs. weekly - check their site)",
      "Free users get newer models off-peak but drop to a fallback model at peak hours",
      "Standalone Copilot Pro ($20/mo) retired to new users Oct 2025 (existing subs supported until Aug 1, 2026); consumer paid features now live in Microsoft 365 Premium at $19.99/mo (Copilot in Word/Excel/PowerPoint/Outlook + 6TB OneDrive)",
      "Student angle: verified US college students can get Microsoft 365 Personal with Copilot free for 12 months, then ~50% off (~$4.99/mo) - check their site",
    ],
    url: "https://copilot.microsoft.com",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Todoist",
    category: "Productivity",
    deal: "Generous free tier",
    price: "Free tier · Pro from $5/mo",
    description: "A clean, cross-platform task manager for capturing assignments, due dates, and reminders. The free plan covers most of what a student needs to stay organized.",
    details: [
      "Free \"Beginner\" plan (ongoing, no expiry): 5 active personal projects, 3 filter views, task reminders, 1-week activity history, 5 collaborators per project, 300 tasks per project",
      "Pro: $5/mo billed annually ($60/yr) or $7/mo monthly — unlocks 300 projects, calendar layout, 150 filters, custom reminders, and full history",
      "Business (teams): $8/user/mo billed annually ($96/yr) or $10/mo monthly",
      "No official student discount (confirmed by Todoist's help center); occasional third-party codes (e.g. Student Beans) appear periodically",
    ],
    url: "https://www.todoist.com",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "ClickUp",
    category: "Productivity",
    deal: "Free Forever plan",
    price: "Free tier · Paid from $7/user/mo",
    description: "ClickUp is an all-in-one workspace for tasks, docs, calendars, and goals, so you can manage assignments and group projects in one place. The free plan works fine for a solo student, though cloud storage is capped at 60MB.",
    details: [
      "Free Forever plan: unlimited tasks and unlimited members, plus docs, Kanban boards and calendar view",
      "Free tier limits: only 60MB storage and 1 form",
      "Paid plans: Unlimited $7/user/mo billed yearly (~$10 monthly), Business $12/user/mo billed yearly (~$19 monthly), Enterprise custom",
      "Academic discount is mentioned on ClickUp's education page but is vague and institution-focused - check their site",
    ],
    url: "https://clickup.com",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Taskade",
    category: "Productivity",
    deal: "Free-forever plan",
    price: "Free · Pro from $10/mo",
    description: "Taskade is an all-in-one workspace for notes, tasks, outlines, mind maps, and AI agents (now positioned as an AI app builder too). The free-forever plan lets a student organize projects and try the AI features without paying.",
    details: [
      "Free forever: 1 user, core task/notes/outline/mind-map tools, up to 3 live apps, and ~250 MB storage - check their site for current caps",
      "Free AI is capped: a one-time ~3,000 AI credit allotment, 1 AI agent, and 3 automations",
      "Pro from $10/mo billed annually (higher month-to-month, ~$16) adds 50,000 monthly AI credits, 100 GB storage, and unlimited agents/automations - check their site",
      "Student angle: 50% off Pro via Student Beans or the 'STUDENTS50' code (verification required), but the base free plan needs no student proof",
    ],
    url: "https://www.taskade.com",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Obsidian",
    category: "Productivity",
    deal: "Free, no limits",
    price: "Free · Sync $4/mo, Publish $8/mo",
    description: "A free, local-first note-taking app that stores everything as plain Markdown files on your own device, with backlinks and a graph view for connecting ideas. Good for building a personal knowledge base, class notes, or research.",
    details: [
      "Core app is completely free with no limits: unlimited vaults, no sign-up required, works offline",
      "Includes graph view, Canvas, Bases, and thousands of community plugins at no cost",
      "Optional paid add-ons: Sync $4/mo annual ($5 monthly); Publish $8/mo annual ($10 monthly)",
      "Students, faculty, and nonprofit staff get 40% off Sync and Publish",
    ],
    url: "https://obsidian.md",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Goblin.tools",
    category: "Productivity",
    deal: "Completely free, no account needed",
    price: "Free · apps ~$2.99 one-time",
    description: "Goblin.tools is a set of small single-task AI helpers that break big assignments into manageable steps, reword messages, estimate how long tasks take, and more. The whole website is free to use with no sign-up or paywall.",
    details: [
      "Web version is fully free: every tool (Magic ToDo, Formalizer, Judge, Estimator, Professor, Consultant, Compiler, Chef, etc.) with no account and no paywall",
      "No usage limits or personal details required to use the site; kept free by sponsors and ad-free",
      "Optional iOS/Android apps are a one-time purchase (~$2.99 on the App Store; price varies by store/region — check their site) that funds the free website",
      "Popular with ADHD and neurodivergent students for breaking overwhelming tasks into small steps",
    ],
    url: "https://goblin.tools",
    pricing: "free",
    popular: false,
    verified: false,
  },
  {
    name: "Elicit",
    category: "Research",
    deal: "Generous free tier",
    price: "Free tier · Pro $49/mo",
    description: "Elicit is an AI research assistant that searches academic papers, summarizes them, and answers questions with cited sources. The free tier covers unlimited paper search and summaries, which is genuinely useful for literature reviews and coursework.",
    details: [
      "Free Basic plan: unlimited search across 138M+ papers, unlimited paper summaries, and unlimited full-text chat-with-papers",
      "Free plan limits usage of the Research Agent and Research Reports features; includes Zotero import",
      "Paid Pro $49/mo (35% off billed annually); Scale $169/mo; Enterprise custom — verify current pricing on their site",
      "No official student discount; sign up with an academic email and use the free tier for lit reviews",
    ],
    url: "https://elicit.com",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Consensus",
    category: "Research",
    deal: "Genuine free tier + 40% student discount on Pro",
    price: "Free tier · Pro ~$10/mo",
    description: "Consensus is an AI academic search engine that answers research questions using 200M+ peer-reviewed papers and shows the citations behind each claim. The ongoing free plan covers searches and AI summaries, which is handy for essays and literature reviews.",
    details: [
      "Free plan (ongoing, no credit card): unlimited basic searches across 200M+ papers, plus about 15 Pro AI messages, 3 Deep Searches, and ~10 study snapshots per month (exact caps vary by source — check their site)",
      "Pro is ~$10/mo billed annually (~$120/yr); the month-to-month rate is higher (~$15–20/mo) — check their site",
      "Students/faculty get 40% off Pro with a verified .edu/.ac email (roughly ~$6/mo — check their site)",
      "Heads-up: several Trustpilot reviews report surprise annual-renewal charges (~$107.88), so watch the auto-renew if you upgrade",
    ],
    url: "https://consensus.app",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Semantic Scholar",
    category: "Research",
    deal: "Completely free, no paywall",
    price: "Free",
    description: "A free, AI-powered academic search engine from the non-profit Allen Institute for AI (Ai2). It helps students find, summarize, and understand scientific papers across 236M+ studies in every field.",
    details: [
      "Completely free with no paid tiers or paywalls; search 236M+ papers across all disciplines",
      "AI features: TLDR one-sentence summaries, Semantic Reader PDF viewer, Highly Influential Citations, and personalized research feeds",
      "Free developer REST API for paper, author, and citation data; optional free API key unlocks higher rate limits",
      "Run by the non-profit Allen Institute for AI (Ai2); no cost or student sign-up required to search",
    ],
    url: "https://www.semanticscholar.org/",
    pricing: "free",
    popular: false,
    verified: false,
  },
  {
    name: "ResearchRabbit",
    category: "Research",
    deal: "Generous free tier",
    price: "Free · RR+ $10/mo",
    description: "ResearchRabbit maps academic literature visually, showing how papers, authors, and topics connect so you can build a literature review from a handful of starting papers. The free plan covers most student research needs.",
    details: [
      "Free Forever plan ($0): unlimited searches and collections, collaboration, and up to 50 seed articles",
      "Searches 310M+ papers with visual citation and co-author maps",
      "Optional RR+ tier is $10/mo (annual) or $12.50/mo (monthly): raises seed limit to 300, adds advanced controls, multiple projects, and alerts",
      "No dedicated student discount, but the free tier suits most student lit reviews",
    ],
    url: "https://www.researchrabbit.ai",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "SciSpace",
    category: "Research",
    deal: "Free plan + 30% student discount",
    price: "Free tier · Premium ~$12/mo",
    description: "SciSpace is an AI research assistant for finding, reading, and understanding academic papers — chat with PDFs, run literature reviews, and pull data from studies. The free plan covers light research use without paying, and there's a 30% academic discount on paid plans.",
    details: [
      "Free plan: ~100 credits/month with limited literature-review searches and limited chat-with-PDF / AI Copilot actions",
      "Premium ~$12/mo billed annually (~$20/mo monthly): 1,200 credits, unlimited lit-review searches and paper summaries (check their site)",
      "Students/academics: 30% off with code SCI30 (IND30 in India); University Program offers free licenses for eligible students",
      "Separate writing/editor tool (formerly Typeset) has its own free plan with limited exports and document previews",
    ],
    url: "https://scispace.com",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Connected Papers",
    category: "Research",
    deal: "Free 5 graphs every month",
    price: "Free · 5 graphs/mo (Academic ~$6/mo)",
    description: "A visual literature-mapping tool: paste one paper and it builds a graph of related work arranged by similarity, so you can spot the key papers and gaps fast. Free to use, and no account is needed to start.",
    details: [
      "Free plan: 5 new graphs per month with all features; works without an account (a free account adds saved papers and graph history)",
      "Each graph maps the most relevant prior and derivative works (~50 papers) by similarity to speed up a literature review",
      "Academic plan lifts the monthly cap (unlimited graphs) for ~$6/mo billed annually; quarterly billing costs a bit more per month, and some regions see lower local pricing - check their site",
      "Academic plan is meant for students, academics and personal use; a separate Business plan (~$20/mo) covers commercial use",
    ],
    url: "https://www.connectedpapers.com",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Wordtune",
    category: "Writing",
    deal: "Generous free tier",
    price: "Free tier · Advanced $6.99/mo",
    description: "Wordtune is an AI writing assistant that rewrites, paraphrases, summarizes, and checks grammar. The free plan covers light daily use for essays, emails, and assignments with no credit card required.",
    details: [
      "Free (Basic) plan: 10 rewrites & AI suggestions per day, 3 AI summaries per month, unlimited spelling and grammar checks; no credit card required",
      "Advanced $6.99/mo (~$4.89/mo billed annually): 30 rewrites/day, 15 summaries/month",
      "Unlimited $9.99/mo (~$6.99/mo billed annually): unlimited rewrites and summaries",
      "Student/educator discount: 30% off monthly or annual with a valid .edu email, applied via Wordtune's academic discount page (can't be combined with annual savings) — check their site",
    ],
    url: "https://www.wordtune.com",
    pricing: "freemium",
    trial: true,
    trialLength: "3-day trial",
    popular: false,
    verified: false,
  },
  {
    name: "LanguageTool",
    category: "Writing",
    deal: "Generous free tier",
    price: "Free tier · Premium ~$5/mo",
    description: "A multilingual grammar, spelling, and punctuation checker that runs in the browser and as add-ons for Chrome, Word, and Google Docs. The free plan handles everyday essays and emails in 30+ languages without paying.",
    details: [
      "Free plan: checks spelling, grammar, punctuation and basic style in 30+ languages, with a limit of roughly 10,000 characters per check.",
      "Premium adds advanced style/'picky mode' suggestions, paraphrasing, and a much higher character limit (~100,000+; exact figure varies by source, so check their site).",
      "Premium runs ~$5/mo on longer plans; annual is a bit higher and month-to-month is much pricier (~$20-25/mo). A 20% limited-time discount and a 14-day money-back guarantee are currently shown, so check their site.",
      "Students, teachers and professors can get up to 20% off Premium via the EDUCATION coupon after verifying status (UNiDAYS/Student Beans/SheerID/ID.me).",
    ],
    url: "https://languagetool.org",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Hemingway Editor",
    category: "Writing",
    deal: "Genuine free web editor",
    price: "Free tier · Plus $10/mo",
    description: "A free web editor that flags hard-to-read sentences, passive voice, and adverbs so your essays and papers read more clearly. The free tier only highlights issues; AI rewrites and grammar fixes are paid.",
    details: [
      "Free web app (no login): paste text for a readability grade plus highlights for dense sentences, passive voice, adverbs, and simpler-word swaps",
      "Free tier flags problems but does not auto-fix or rewrite them",
      "Editor Plus adds AI rewrites, grammar checking, and 5,000 AI sentences/mo: $10/mo or $100/yr ($8.33/mo); a 10K-sentence tier runs $12.50/mo",
      "No student discount found; a 2-week Plus trial (no credit card, cancels automatically) is available",
    ],
    url: "https://hemingwayapp.com",
    pricing: "freemium",
    trial: true,
    trialLength: "14-day trial",
    popular: false,
    verified: false,
  },
  {
    name: "Jenni AI",
    category: "Writing",
    deal: "Free tier for academic writing",
    price: "Free tier · Plus $12/mo",
    description: "AI writing assistant built for academic work — it autocompletes essays and research papers grounded in real sources and adds in-text citations in APA, MLA, Chicago and more. The free plan lets you draft and cite without a credit card.",
    details: [
      "Free plan (no credit card): 10 AI autocompletes/day, 5 AI chat messages, 5 AI edits, 10 PDF uploads",
      "Paid Plus $12/mo (5,000 autocompletes/mo, 500 edits, 500 chat); Pro $29/mo unlimited — annual billing advertised at ~60% off; check their site",
      "Cites from 200M+ papers with 10,000+ styles (APA, MLA, Chicago, IEEE), imports PDFs and Zotero/Mendeley libraries",
      "No official student-only plan; a student discount is promoted via third-party sites (Student Beans) — check their site",
    ],
    url: "https://jenni.ai",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Adobe Express",
    category: "Design",
    deal: "Generous free tier",
    price: "Free tier · Premium ~$9.99/mo",
    description: "Adobe's browser and mobile design app for quick graphics, social posts, short videos, and flyers. The free plan is genuinely usable for students who make a handful of designs a month.",
    details: [
      "Free plan (ongoing, no card needed): 100,000+ templates, 1M+ stock assets, 4,000+ fonts, basic photo/design/video editing, 5GB storage, and ~25 generative AI credits/month",
      "Free-plan limits: watermark on some exports, 300MB upload cap, and premium templates/assets locked",
      "Premium is ~$9.99/mo or ~$99.99/yr (100GB storage, 250 AI credits/mo) — check their site as Adobe pricing shifts",
      "Student angle: free for K-12 schools when the institution deploys it; a promotional 6-month free Premium offer for students has also run (region/time-limited, not permanent)",
    ],
    url: "https://www.adobe.com/express/",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Framer",
    category: "Design",
    deal: "Basic plan free for students",
    price: "Free tier · Basic $10/mo (free for students)",
    description: "Framer is a no-code website builder where you design and publish a live site straight from a visual canvas. The free plan hosts a real site on a Framer subdomain, and verified students get the paid Basic plan free.",
    details: [
      "Free plan ($0): 1,000 pages, 10 CMS collections, up to 3 editors, 1 GB bandwidth, hosted on a free Framer subdomain with a Framer badge; 500 AI credits/mo",
      "Free plan has no custom domain (a paid plan is required for that)",
      "Paid: Basic ~$10/mo, Pro ~$30/mo (rates shown are for annual billing; monthly billing is higher — check their site)",
      "Students: verified students get Basic free (~$120/yr value) with custom domain, CMS, and 1,000 AI credits/mo; renewable every 11 months while enrolled",
    ],
    url: "https://www.framer.com/",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Microsoft Designer",
    category: "Design",
    deal: "Free with any Microsoft account",
    price: "Free · M365 $9.99/mo",
    description: "Microsoft's free AI design app for social posts, invites, and graphics. Works with any Microsoft account, exports carry no watermark, and it uses DALL-E 3 for AI image generation.",
    details: [
      "Free tier: sign in with any Microsoft account; free accounts get ~15 AI credits/month for image generation and AI edits (credits reportedly don't roll over) - check their site",
      "Free exports carry no watermark, unlike many competitors",
      "Templates plus DALL-E 3-powered image generation and layout tools",
      "No standalone Designer plan; paid access is bundled into Microsoft 365 Personal ($9.99/mo, 60 credits shared across Copilot + Designer), and students on a school Microsoft 365 Education account get access at no cost",
    ],
    url: "https://designer.microsoft.com",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Photopea",
    category: "Design",
    deal: "Free Photoshop alternative",
    price: "Free · Premium $5/mo",
    description: "Photopea is a free, browser-based image editor that opens and edits PSD files and works much like Photoshop, with no download or account needed. The full pro toolset is free (ad-supported); an optional $5/month Premium plan just removes the ads.",
    details: [
      "Free forever: full editor with layers, masks, vector tools, 40+ file formats including PSD, plus AI background removal, all in the browser with no account required.",
      "The free version is ad-supported; ads are the main limitation.",
      "Premium removes ads for $5/month (~$50/year); per Photopea's official blog it adds no extra features and mainly supports development.",
      "No dedicated student discount, but it is genuinely free for everyone - a strong free stand-in for Photoshop.",
    ],
    url: "https://www.photopea.com",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Leonardo AI",
    category: "Design",
    deal: "Generous free tier",
    price: "Free tier · paid from $12/mo ($10/mo annual)",
    description: "Leonardo AI is an AI image and asset generator handy for mockups, moodboards, concept art, and design coursework. The free plan gives you 150 tokens a day with no card required, though free generations are public in the community feed rather than private.",
    details: [
      "Free plan: 150 fast tokens/day, reset daily with no rollover (enough for roughly 30+ images, varies by model and resolution)",
      "Free generations are public in the community feed - not private",
      "Paid plans: $12/mo ($10/mo billed annually), plus $30/mo and $60/mo tiers",
      "No official student discount confirmed - only coupon aggregators claim one; check their site",
    ],
    url: "https://leonardo.ai",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
];
