// ============================================================
// DEALS CATALOG
//
// IMPORTANT: This is SAMPLE data to show the site working.
// Before launch, verify every offer on the company's own site
// and set verified: true. Replace each url with your affiliate
// link once you've joined that company's program.
//
// Fields:
//   popular    — true = shows on the homepage "Popular deals" view
//   pricing    — "free" | "freemium" | "trial" | "discount" (drives the Free filter)
//   price      — short price string shown on cards ("Free", "Free tier · Pro $20/mo").
//                Prices marked ~ are approximate — confirm before launch.
//   details    — "What you get" bullets on the deal page. Keep them factual
//                and specific (limits, trial lengths, eligibility).
//   rating     — Trustpilot score scraped on the date in `checked`. Refresh
//                periodically. Under 20 reviews the UI hides the score.
//   trial      — true = also has a free trial of a paid plan
//   trialLength— free-trial duration string (e.g. "30-day Pro trial"); shows a pill on the card
//   screenshot — true = show a live screenshot of the tool's site (opt-in)
//   image      — card/hero image (vendor og image or press-kit PNG/GIF)
//   gallery    — extra images for the deal page thumbnail strip (optional)
// ============================================================

const DEALS = [
  {
    name: "GitHub Student Developer Pack",
    category: "Coding",
    deal: "Free with a school email",
    price: "Free for students",
    description: "GitHub Copilot Pro plus dozens of dev tools, free while you're a student. The single best student bundle on the internet.",
    details: [
      "GitHub Copilot Pro free while you're a verified student",
      "Dozens of partner tools included: cloud credits, free domains, IDEs, and more",
      "Free for as long as you're enrolled — re-verify each year",
      "Requires proof of enrollment (school email or student ID)",
    ],
    url: "https://education.github.com/pack",
    image: "images/github.png",
    rating: { score: 2.0, count: 253, source: "Trustpilot", url: "https://www.trustpilot.com/review/github.com", checked: "2026-07-23" },
    pricing: "free",
    popular: true,
    screenshot: true,
    verified: false,
  },
  {
    name: "Notion",
    category: "Productivity",
    deal: "Free Plus plan for students",
    price: "Free for students",
    description: "Notes, docs, and planning with Notion AI available as an add-on. The education plan is free with a school email.",
    details: [
      "Education Plus plan free with a school email",
      "Unlimited pages and blocks, file uploads, and version history",
      "Notion AI is a paid add-on — not included in the free education plan",
      "Free for as long as you have a valid school email",
    ],
    url: "https://www.notion.so/students",
    image: "images/notion.png",
    rating: { score: 2.3, count: 418, source: "Trustpilot", url: "https://www.trustpilot.com/review/notion.so", checked: "2026-07-23" },
    pricing: "free",
    popular: true,
    screenshot: true,
    verified: false,
  },
  {
    name: "Perplexity",
    category: "Research",
    deal: "Student offer",
    price: "Free tier · Pro $20/mo",
    description: "AI answer engine with cited sources — great for research without the hallucinated citations. Runs student promotions on Pro.",
    details: [
      "Free tier: unlimited quick searches with cited sources",
      "Pro: more advanced searches per day, file uploads, and model choice",
      "Runs student promotions on Pro periodically — check their site",
    ],
    url: "https://www.perplexity.ai/",
    image: "images/perplexity.jpg",
    rating: { score: 1.5, count: 714, source: "Trustpilot", url: "https://www.trustpilot.com/review/perplexity.ai", checked: "2026-07-23" },
    pricing: "discount",
    popular: true,
    verified: false,
  },
  {
    name: "Grammarly",
    category: "Writing",
    deal: "Free tier + education plans",
    price: "Free tier · Premium ~$12/mo",
    description: "Grammar, tone, and clarity checking everywhere you write. Solid free tier; some schools cover Premium.",
    details: [
      "Free: grammar, spelling, and tone basics everywhere you write",
      "Premium: full-sentence rewrites, plagiarism detection, citation support",
      "Premium is ~$12/mo billed annually — but check if your school licenses it for free first",
    ],
    url: "https://www.grammarly.com/edu",
    image: "images/grammarly.png",
    rating: { score: 3.3, count: 10461, source: "Trustpilot", url: "https://www.trustpilot.com/review/grammarly.com", checked: "2026-07-23" },
    pricing: "freemium",
    popular: true,
    verified: false,
  },
  {
    name: "Quizlet",
    category: "Studying",
    deal: "Free tier + Plus discount",
    price: "Free tier · Plus ~$7.99/mo",
    description: "Flashcards and practice tests with AI-generated study modes from your own notes.",
    details: [
      "Free: flashcards, practice tests, and basic study modes",
      "Plus: ad-free, offline access, and unlimited AI-powered study modes",
      "New users typically get a free trial of Plus — length varies by promo",
    ],
    url: "https://quizlet.com/",
    rating: { score: 1.3, count: 640, source: "Trustpilot", url: "https://www.trustpilot.com/review/quizlet.com", checked: "2026-07-23" },
    pricing: "freemium",
    trial: true,
    popular: true,
    verified: false,
  },
  {
    name: "Otter.ai",
    category: "Productivity",
    deal: "Education discount",
    price: "Free tier · student discount on Pro",
    description: "Records and transcribes lectures in real time, then gives you an AI summary and searchable notes.",
    details: [
      "Free: 300 transcription minutes per month, 30 min per conversation",
      "Pro: 1,200 minutes/month, longer conversations, better exports",
      "Students and teachers get a discount on Pro with a school email",
    ],
    url: "https://otter.ai/education",
    image: "images/otter.png",
    rating: { score: 3.1, count: 570, source: "Trustpilot", url: "https://www.trustpilot.com/review/otter.ai", checked: "2026-07-23" },
    pricing: "discount",
    popular: false,
    verified: false,
  },
  {
    name: "Gamma",
    category: "Design",
    deal: "Generous free tier",
    price: "Free tier · paid from ~$8/mo",
    description: "Generates full slide decks from a prompt. The fastest way to turn an outline into a presentation.",
    details: [
      "Free: AI deck generation with starting credits, share and present online",
      "Paid plans: unlimited AI creation and watermark-free exports",
      "No credit card needed for the free tier",
    ],
    url: "https://gamma.app/",
    image: "images/gamma.png",
    rating: { score: 1.7, count: 118, source: "Trustpilot", url: "https://www.trustpilot.com/review/gamma.app", checked: "2026-07-23" },
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Wolfram|Alpha Pro",
    category: "Studying",
    deal: "Student pricing",
    price: "Student plan from ~$5/mo",
    description: "Step-by-step math solutions, not just answers. Discounted Pro plan for students.",
    details: [
      "Pro: step-by-step solutions for math, physics, and chemistry problems",
      "Practice problems with hints, and photo input for handwritten math",
      "Discounted student pricing — cheaper than a single tutoring session per year",
    ],
    url: "https://www.wolframalpha.com/pro/pricing/students",
    image: "images/wolfram.png",
    rating: { score: 3.3, count: 3, source: "Trustpilot", url: "https://www.trustpilot.com/review/wolframalpha.com", checked: "2026-07-23" },
    pricing: "discount",
    popular: false,
    verified: false,
  },
  {
    name: "Speechify",
    category: "Studying",
    deal: "Free tier",
    price: "Free tier · Premium ~$139/yr",
    description: "Turns readings and PDFs into natural-sounding audio so you can get through them faster.",
    details: [
      "Free: listen to docs, PDFs, and web pages at standard speeds",
      "Premium: natural AI voices, up to 4.5x speed, scan-and-listen for printed pages",
      "Works across phone, browser extension, and desktop",
    ],
    url: "https://speechify.com/",
    image: "images/speechify.jpg",
    rating: { score: 4.7, count: 6662, source: "Trustpilot", url: "https://www.trustpilot.com/review/speechify.com", checked: "2026-07-23" },
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Zotero",
    category: "Research",
    deal: "100% free",
    price: "Free",
    description: "The standard tool for collecting sources and generating citations. Free and open source, with AI plugins available.",
    details: [
      "Completely free, open-source citation manager — no premium upsell",
      "Browser connector saves any source in one click",
      "Word and Google Docs plugins generate citations and bibliographies",
      "Paid only if you want extra cloud sync storage (from $20/yr)",
    ],
    url: "https://www.zotero.org/",
    rating: { score: 3.7, count: 14, source: "Trustpilot", url: "https://www.trustpilot.com/review/zotero.org", checked: "2026-07-23" },
    pricing: "free",
    popular: false,
    screenshot: true,
    verified: false,
  },
  {
    name: "Canva",
    category: "Design",
    deal: "Free tier + Pro trial",
    price: "Free tier · Pro ~$13/mo",
    description: "Design anything — posters, decks, social posts — with built-in AI image and text tools.",
    details: [
      "Free: thousands of templates and basic AI design tools",
      "Pro: premium assets, background remover, brand kits, and more AI credits",
      "30-day free trial of Pro",
      "Heads up: Canva's free education program covers K-12 only, not college",
    ],
    url: "https://www.canva.com/education/",
    image: "images/canva.jpg",
    rating: { score: 4.0, count: 6130, source: "Trustpilot", url: "https://www.trustpilot.com/review/canva.com", checked: "2026-07-23" },
    pricing: "freemium",
    trial: true,
    trialLength: "30-day Pro trial",
    popular: false,
    verified: false,
  },
  {
    name: "ChatGPT",
    category: "Writing",
    deal: "Free tier",
    price: "Free · Plus $20/mo",
    description: "The general-purpose assistant everyone knows. The free tier covers a lot of student use cases.",
    details: [
      "Free: full chat access with daily usage limits",
      "Plus: higher limits, stronger models, file uploads, and image generation",
      "No student discount currently — the free tier is the student play",
    ],
    url: "https://chatgpt.com/",
    image: "images/chatgpt.png",
    rating: { score: 1.2, count: 1094, source: "Trustpilot", url: "https://www.trustpilot.com/review/openai.com", checked: "2026-07-23" },
    pricing: "freemium",
    popular: true,
    verified: false,
  },
  {
    name: "Claude",
    category: "Writing",
    deal: "Free tier + free Pro at partner schools",
    price: "Free tier · Pro $20/mo",
    description: "Claude is an AI assistant for writing, research, and coding with a genuinely usable free tier. Students at universities with a Claude for Education license get Pro-level features free by signing in with their school email; there's no personal student discount otherwise.",
    details: [
      "Free tier ($0): chat, web search, file uploads, memory, and Projects, but with capped usage limits that tighten during high demand",
      "Pro is $20/mo billed monthly, or $17/mo on annual billing (per claude.com/pricing) — check their site as prices change",
      "No individual student discount; Claude for Education gives free Pro only if your university holds a license — sign in with your .edu email to check",
      "No time-limited free trial on Pro; the free tier is the way to try it",
    ],
    url: "https://claude.ai",
    rating: { score: 1.5, count: 1695, source: "Trustpilot", url: "https://www.trustpilot.com/review/claude.ai", checked: "2026-07-23" },
    pricing: "freemium",
    popular: true,
    verified: false,
  },
  {
    name: "Google Gemini",
    category: "Research",
    deal: "Free tier + 1-month Pro trial",
    price: "Free tier · Pro $19.99/mo",
    description: "Google's AI assistant for writing, coding, and studying, with a Deep Research mode that pulls together and summarizes sources. Free with any Google account; paid plans add stronger models, higher usage limits, and more storage.",
    details: [
      "Free tier (any Google account): chat, image generation, Canvas and Gems on Gemini Flash, plus Deep Research (about 5 reports/month) and 15 GB storage, with daily usage limits",
      "Google AI Pro is $19.99/mo — adds the top Gemini 3 Pro model, higher limits, Veo video, and Gemini in Gmail, Docs and Sheets; first-time users get a 1-month free trial that auto-renews",
      "A cheaper Google AI Plus tier is $4.99/mo (2x limits, 200 GB storage) if Pro is more than you need",
      "Google's year-long free AI Pro student offer has ended — no current student discount is confirmed, so check their site",
    ],
    url: "https://gemini.google.com/",
    pricing: "freemium",
    trial: true,
    trialLength: "1-month Pro trial",
    popular: true,
    verified: false,
  },
  {
    name: "Cursor",
    category: "Coding",
    deal: "Free Hobby tier (no card)",
    price: "Free tier · Pro $20/mo (~$16/mo annual)",
    description: "Cursor is an AI-powered code editor (a VS Code fork) that autocompletes and rewrites code from chat. Students can code for free on the Hobby tier with no credit card, then decide whether Pro is worth $20/mo.",
    details: [
      "Free Hobby tier: no credit card, but limited AI Agent requests and limited Tab completions",
      "Pro is $20/mo month-to-month, or ~$16/mo billed annually (20% off) — check their site to confirm",
      "New accounts may get a short full-Pro trial, but the official pricing page lists none and reports conflict in 2026 — don't count on it",
      "Student gotcha: the free-year student Pro offer closed to new signups on June 25, 2026; now only occasional campus/event credits, so no reliable universal student discount",
    ],
    url: "https://cursor.com/",
    pricing: "freemium",
    popular: true,
    verified: false,
  },
  {
    name: "Overleaf",
    category: "Studying",
    deal: "Free tier + student discount",
    price: "Free tier · Student $10/mo",
    description: "Overleaf is a browser-based LaTeX editor for writing papers, theses, and problem sets with real-time collaboration and no local setup. The free tier covers solo writing, and there's a discounted student plan — but check whether your university already provides Overleaf Professional for free before paying.",
    details: [
      "Free plan: unlimited projects but only 1 collaborator per project, a short compile-timeout limit, and AI assist capped at 5 uses/day",
      "Student plan $10/mo (or $98/yr, ~18% off) adds 10 collaborators and a much longer compile timeout; requires verified enrollment",
      "Non-student tiers: Standard $21/mo ($199/yr) and Professional $42/mo ($399/yr); annual billing saves ~20%",
      "Many universities offer Overleaf Professional free through a campus/library site license — check with your school before subscribing",
    ],
    url: "https://www.overleaf.com",
    pricing: "freemium",
    trial: true,
    trialLength: "7-day trial",
    popular: false,
    verified: false,
  },
  {
    name: "QuillBot",
    category: "Writing",
    deal: "Free tier + student discount",
    price: "Free tier · Premium $20/mo ($8/mo annual)",
    description: "QuillBot is a paraphrasing and grammar tool for rewriting, summarizing, and cleaning up drafts. The free tier covers light use, and verified students can get Premium at a reduced annual rate.",
    details: [
      "Free tier: paraphraser capped at 125 words per run with 2 modes (Standard + Fluency) plus basic grammar checking — no credit card, no time limit",
      "Premium unlocks unlimited paraphrasing, all paraphrasing modes, and a plagiarism checker (25,000 words/mo); $19.95/mo monthly or $8.33/mo billed annually ($99.95/yr)",
      "Student discount: 25% off the annual plan (~$6.25/mo) with student/.edu email verification — confirm current price on their site",
      "No time-limited free trial; a 3-day money-back guarantee is the only refund window",
    ],
    url: "https://quillbot.com/premium",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Figma",
    category: "Design",
    deal: "Free Pro for verified students",
    price: "Free for students · Pro $20/mo",
    description: "Figma is a collaborative interface-design tool for UI design, prototyping, and FigJam whiteboarding. Verified higher-ed students and educators get the paid Professional plan free for a year (renewable), and there's a free Starter tier open to everyone.",
    details: [
      "Student deal: verified higher-ed students & educators get the full Professional plan free for 1 year from approval, renewable while eligible — apply with a school email and proof of enrollment",
      "Free Starter tier (no student status needed): 3 Figma Design + 3 FigJam files, 1 project, unlimited personal drafts, up to 2 editors/file, 30-day version history",
      "Paid Professional (non-students): $20/mo per full seat billed monthly, or $16/mo billed annually — check their site to confirm",
      "No time-limited free trial of paid plans; the free Starter tier is the entry point. Education access is region-limited and needs re-verification to renew",
    ],
    url: "https://www.figma.com/education/",
    pricing: "free",
    popular: true,
    verified: false,
  },
  {
    name: "NotebookLM",
    category: "Studying",
    deal: "Free tier + 1-month Pro trial",
    price: "Free tier · Plus ~$5/mo · Pro $20/mo",
    description: "Google's AI research assistant that turns your own PDFs, slides, and notes into summaries, study guides, quizzes, flashcards, and audio overviews, all grounded in the sources you upload. The free tier is generous enough for most coursework and needs no credit card.",
    details: [
      "Free forever tier: 100 notebooks, 50 sources each, 50 chats/day, and 3 audio + 3 video overviews per day — no card required",
      "Paid upgrades are bundled with Google's AI plans: NotebookLM Plus via Google AI Plus (~$5/mo) or NotebookLM Pro via Google AI Pro ($19.99/mo, raising limits to ~300 sources per notebook)",
      "Google AI Pro includes a 1-month free trial that unlocks Pro limits",
      "Gotcha: the free 12-month student offer ended April 30, 2026, and Google no longer lists a student-specific price — students pay standard rates or use the free tier",
    ],
    url: "https://notebooklm.google.com/",
    pricing: "freemium",
    trial: true,
    trialLength: "1-month Pro trial",
    popular: false,
    verified: false,
  },
  {
    name: "DeepL",
    category: "Writing",
    deal: "Free tier + 30-day trial",
    price: "Free tier · Individual $8.74/mo (annual)",
    description: "DeepL is an AI translation and writing tool that's handy for reading foreign-language sources and drafting text in another language. The free tier covers light coursework, and paid plans raise the character and document limits.",
    details: [
      "Free version: 50,000 characters/month plus 1 document translation/month (files up to 5 MB)",
      "Individual plan is $8.74/mo billed annually (monthly billing costs more, ~$10.40/mo) and adds 300,000 chars/month + 3 documents/month (up to 30 MB)",
      "Paid plans include a 30-day free trial, cancel anytime",
      "No student or education discount as of mid-2026; listed prices are USD and vary by region, so check their site",
    ],
    url: "https://www.deepl.com/pro",
    rating: { score: 2.4, count: 744, source: "Trustpilot", url: "https://www.trustpilot.com/review/www.deepl.com", checked: "2026-07-23" },
    pricing: "freemium",
    trial: true,
    trialLength: "30-day trial",
    popular: false,
    verified: false,
  },
  {
    name: "Knowt",
    category: "Studying",
    deal: "Free tier + 15% student discount",
    price: "Free tier · Ultra $24.99/mo or $149.99/yr",
    description: "Knowt is a free Quizlet alternative that turns your notes, PDFs, lectures, and videos into flashcards, quizzes, and study guides, with an AI assistant called Kai. The free tier covers everyday coursework; paid Ultra removes AI usage limits.",
    details: [
      "Free Basic plan: unlimited flashcards & notes, free study modes (Learn, matching, spaced repetition, practice tests), and browsing millions of pre-made sets — no credit card (AI features are usable but monthly-capped)",
      "Paid Ultra plan: $24.99/mo or $149.99/yr (~$12.49/mo effective) unlocks unlimited AI summaries, unlimited Kai chat, and auto-graded assessments",
      "Students get 15% off paid plans plus a 1-month free trial via verified programs (UNiDAYS / Student Beans)",
      "A standard (non-student) trial length isn't stated on the official plans page — third-party reviews say ~7 days; check their site before relying on it",
    ],
    url: "https://knowt.com",
    pricing: "freemium",
    trial: true,
    trialLength: "1-month student trial",
    popular: false,
    verified: false,
  },
  {
    name: "Thea",
    category: "Studying",
    deal: "Free for students",
    price: "Free tier · ~$10/mo ($40/yr)",
    description: "Thea is an AI study app that turns your notes, PDFs, lecture videos, or a pasted YouTube link into flashcards, quizzes, study guides, and practice tests. It's currently free for students, with an optional paid subscription for extra access.",
    details: [
      "Free tier: create a free account and use it for free — the pricing page explicitly says \"Students, it's FREE!\" (some sources describe this as free during beta, so it could change)",
      "Paid option: the iOS \"Early Access\" in-app subscription is ~$10/mo or ~$40/yr; there is no published web pricing table, so check their site",
      "Turns your own uploads — handwritten notes, PDFs, lecture videos, or a pasted YouTube link — into flashcards, quizzes, summaries, and tests using active recall",
      "No time-limited free trial; the free tier is the free access. Educators/institutions need a custom quote (email info@thea.study)",
    ],
    url: "https://www.thea.study",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "NotesXP",
    category: "Studying",
    deal: "Free tier + affordable Pro",
    price: "Free tier · Pro $9/mo · $59/yr",
    description: "NotesXP turns PDFs, textbook photos, and lecture recordings into structured notes, flashcards, quizzes, and mind maps. It's an Apple-only app (iPhone, iPad, Mac) with a free tier that needs no account.",
    details: [
      "Free tier gives core features with no required account and no ads, and iCloud sync is automatic; the exact free-tier cap on study sets isn't published — check their site",
      "Pro unlocks unlimited study sets for $9/mo or $59/yr as an Apple App Store in-app purchase; the website doesn't list prices, so confirm in-app",
      "No time-limited free trial, and no verified student/education discount — pricing is only marketed as 'student-friendly'",
      "Apple-only: iPhone/iPad (iOS 15.8+), Mac (macOS 13, M1+), and Apple Vision. No Android app and no web app",
    ],
    url: "https://notesxp.app/",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Mindomax",
    category: "Studying",
    deal: "Premium free until 2028",
    price: "Free tier · Premium free until 2028 (~$5.99/mo after)",
    description: "Mindomax turns PDFs, lecture audio, photos of notes, or plain text into flashcards with spaced repetition and an AI tutor. Its Premium plan is currently free for everyone through 2028.",
    details: [
      "Free tier: one box with unlimited cards, spaced-repetition scheduling, progress analytics, CSV export, and a basic AI assistant (search results cite a 3 AI-requests/day cap; not stated on the live pricing page)",
      "Premium: unlimited boxes, 90 daily AI requests, 450,000+ ready-made cards, PDF/audio/image card generation, LaTeX editor, and AI tutor",
      "Premium is currently free until 2028 (launch promo). The App Store lists a $5.99/mo Premium in-app purchase as the regular price; the website shows only '$0 free until 2028'",
      "No dedicated student/education discount found. Runs on web, iOS, Android, and Mac; launched Nov 2025",
    ],
    url: "https://www.mindomax.com/",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "BrainDen",
    category: "Studying",
    deal: "Free tier, no card needed",
    price: "Free tier · Pro ~$20/mo (~$100/yr)",
    description: "BrainDen turns your lectures, PDFs, videos, audio, and photos into AI-generated notes, flashcards, quizzes, and mind maps, with spaced repetition and a Feynman study mode. Free to start with no card required.",
    details: [
      "Free plan starts with no card: a small number of recordings (~3) plus AI notes, flashcards, quizzes, and mind maps",
      "Pro is $19.99/mo, $49.99 for 6 months, or $99.99/yr per the US App Store listing; web/subscription prices may differ, so check their site",
      "No time-limited free trial and no student/education discount were found; the free tier is the main student value",
      "Official site is brainden.app (app at learn.brainden.app) — 'brainden.ai' is not the real domain",
    ],
    url: "https://www.brainden.app/",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
  {
    name: "Solvo",
    category: "Studying",
    deal: "Free tier + 3-day trial",
    price: "Free tier · Premium ~$6.99/wk or ~$39.99/yr",
    description: "Solvo is a phone app that scans homework problems and returns step-by-step solutions across math, science, and writing, plus AI flashcards and quiz/test prep. A free tier covers occasional use, while a paid subscription lifts the daily usage limits.",
    details: [
      "Free tier lets you solve a limited number of problems per day; Premium removes usage limits and adds OCR scanning, longer answers, and faster responses",
      "3-day free trial that auto-renews into a weekly subscription (~$6.99/wk); a discounted annual plan (~$39.99/yr) is also offered — prices vary by region and promo, so check their site",
      "No student-specific discount or education program was found; this is a standard consumer app subscription (cancel before renewal to avoid charges)",
      "Official app is solvo.app (iOS/Android, by AIBY) — not solvo.ai, which is an unrelated freight/logistics company",
    ],
    url: "https://solvo.app/",
    pricing: "freemium",
    trial: true,
    trialLength: "3-day trial",
    popular: false,
    verified: false,
  },
  {
    name: "FlashRecall",
    category: "Studying",
    deal: "Free tier + paid Premium",
    price: "Free tier · Premium ~$15/mo (~$80/yr)",
    description: "FlashRecall turns your notes, PDFs, photos, audio, and YouTube links into AI flashcards and drills them with spaced repetition and active recall. A free tier covers light studying, and a paid Premium plan removes the AI-generation and review limits.",
    details: [
      "Free tier lets you create and study flashcards with limits for light studying; Premium unlocks unlimited AI generation and study sessions, plus offline access and cross-device sync",
      "Premium pricing isn't published on the site or App Store; third-party snippets suggest roughly $14.99/mo, $79.99/yr, or a ~$9.99/week option — unconfirmed, so check their site",
      "No dedicated student or education discount found; the app positions its ongoing free tier as the alternative to paid competitors' discounts",
      "No time-limited free trial — the free plan is ongoing but limited. Available on the iOS App Store and as a web app; made by TMBC Pte Ltd (Singapore)",
    ],
    url: "https://flashrecall.app/",
    pricing: "freemium",
    popular: false,
    verified: false,
  },
];
